[package]
name = "psx"
version = "0.1.0"
authors = ["Amjad Alsharafi <amjadsharafi10@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
psx-core = { path = "./psx-core", version = "" }
env_logger = "0.8.3"
glium = "0.29.1"

[workspace]
members = [
    "psx-core"
]

